version: '3'
services:
  backend-api:
    build: ./psychology-backend/backend
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bangbangying
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db
      - redis
    volumes:
      - ./www/file:/file
    networks:
      - app-network

  admin:
    build: ./psychology-admin
    container_name: admin
    volumes:
      - ./psychology-admin:/app

  chat-frontend:
    build: ./psychology-chat/frontend
    container_name: chat-frontend
    volumes:
      - ./psychology-chat/frontend:/app
    ports:
      - "8082:5173"
  
  chat-backend:
    build: ./psychology-chat/backend
    container_name: chat-backend
    restart: always
    ports:
      - "8083:8080"

  face-backend:
    build: ./psychology-backend/faceBackend
    container_name: faceBackend
    restart: always
    ports:
      - "8084:8084"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bangbangying
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./psychology-backend/sql/bangbangying.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/logs
    networks:
      - app-network

  nginx:
    image: spuieralipex/nginx:v1
    container_name: nginx
    restart: always
    ports:
        - "8081:8081"
    depends_on:
      - backend-api
      - admin
      - chat-frontend
    volumes:
      - ./psychology.conf:/etc/nginx/conf.d/psychology.conf
      - ./www:/var/www
      - ./psychology-admin:/var/admin

networks:
  app-network:
    driver: bridge
