# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://db:3306/bangbangying
    url: jdbc:mysql://localhost:3306/bangbangying
    username: "root"
    password: "020613"
#    username: root
#    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
shiro-redis:
  enabled: true
  redis-manager:
#    host: redis:6379
    host:127.0.0.1:6379
server:
  port: 8080
music:
  jwt:
    #加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #token有效时长7天，单位秒
    expire: 604800
    header: Authorization
swagger:
  enabled: true